#from . import d
from . import res_partner
from . import cal
from . import a_d
from . import c_l_p
from . import c_l_u
from . import c_l
from . import res_users
from . import s
from . import sql_views
from . import syn
from . import m